### ISSUE TITLE
Built In Time Tracker

### ISSUE THREAD

**Issue by vigoren** [vigoren/foundryvtt-simple-calendar#40]
One thing I have wanted to keep with the Simple Calendar is that it does not require any dependencies to run. While I do plan on making it work with About Time I also want to include its own time tracking code so users don't have to install about time if they do not want too.

This task involves building out the built in time tracker.

Breaking this task off from Issue #16 for easier tracking of its parts.

Current Tasks for the built in time tracker

- [x] Configuration
   - [x] Select which time tracker to use: none, self, about-time.
   - [x] Options:
       - [x] set how many hours in a day
       - [x] minutes in an hour
       - [x] seconds in a minute
   - [x] Advanced options: 
       - [x] ~~seconds in a round of combat~~
       - [x] ~~if time advances automatically or manually~~
       - [x] if automatic how many in game seconds equal a real life second
   - [x] Save new configuration
   - [x] Load configuration on init and apply it
- [x] Time Tracker
    - [x] Set the foundry world time to the time from simple calendar (if needed)
    - [x] Start polling to update time when game is not paused and time advancement is automatic
    - [x] Support for adding to time during combat when each round is finished
- [x] Display Time: find a spot near the calendar to display the current time of day.
- [x] Adjust Time:
    - [x] Add controls to change the current second, minute and hour.
    - [x] Adjust the gm time control interface for a cleaner look and easier interaction.

**Comment by vigoren** [comment]
Added buttons to start and stop the auto clock for the built in time tracker.
Things are working well just need to do some clean up and lots of testing to make sure it is functioning as expected for everyone.

Will need to do some testing for games with multiple GMs to avoid conflicts of bot starting the clock.

**Comment by vigoren** [comment]
Changed my approach for the a little and I think it makes the most sense while allowing the most flexibility.

Adding 2 new general settings

### Game World Time Integration
This will be used to dictate how Simple Calendar interacts with the game world time. There are 4 options, these options each do something different in regards to updating the game world time and reacting to something else updating the game world time. Below is an approximation of how each one works.

Option|Description|Update Game World Time|When Game World Time is Updated
--------|--------------------|-------------------------------------------------|----------------------------------------------------------
None|Doesn't interact with the game world time at all. Keeps simple calendars time tracking isolated and independent|Does not update the game world time|Does not update Simple Calendar when the have world time is updated by something else.
Self|Treats Simple Calendar as the authority source for the game world time.|Updates the game world time to match what is in simple calendar.|Combat round changes will update Simple calendars time. Will ignore updates from all others modules.
Third Party Module|This will instruct Simple Calendar to just display the Time in the have world
